version: '3.5'
services:
  mnarango:
    image: arangodb
    container_name: mn-arangodb
    restart: always
    environment:
      ARANGO_NO_AUTH: '1'
      nolink: '1'
    ports:
      - 127.0.0.1:8529:8529
    volumes:
      - ./moodlenet-storage/db:/var/lib/arangodb3
      - ./moodlenet-storage/db-apps:/var/lib/arangodb3-apps

  nginx:
    image: nginx:1.15-alpine
    container_name: mn-nginx-rv-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mn-network
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/admin:/etc/moodlenet
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./moodlenet-storage/uploads:/var/www/upload
    extra_hosts:
      - host.docker.internal:host-gateway
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: mn-certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  mn-network:
    name: mn-network